services:
  postgres:
    image: postgres:16-alpine
    container_name: academic_db
    environment:
      POSTGRES_DB: academic_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - academic_db_data:/var/lib/postgresql/data

volumes:
  academic_db_data:
